name: dotnet-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore -c Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish output
        run: dotnet publish -c Release -o out

      - name: Upload published artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-publish
          path: out
      - name: List files in published artifact
        run: ls -R out