name: dotnet-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore app

      - name: Build application
        run: dotnet build app --no-restore -c Release

      - name: Run tests
        run: dotnet test app --no-build --verbosity normal

      - name: Publish artifacts
        run: dotnet publish app -c Release -o out

      - name: Upload published artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-publish
          path: out
